-- ============================================================================
-- TICKET-ADV007 — Convert trades to monthly range-partitioned table (Postgres)
--
-- Goal:
--   Convert the existing trades table into a RANGE-partitioned table on
--   trade_date with monthly partitions and a DEFAULT partition.
--
-- WARNING:
--   This migration is destructive. Execute only after taking a backup.
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1 - Rename the existing table
-- ============================================================================

ALTER TABLE trades
RENAME TO trades_legacy;

-- ============================================================================
-- STEP 2 - Create the new partitioned parent table
-- ============================================================================

CREATE TABLE trades
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,

    trade_ref        VARCHAR(30) NOT NULL,

    instrument_id    BIGINT NOT NULL,

    counterparty_id  BIGINT NOT NULL,

    asset_class      VARCHAR(20) NOT NULL,

    side             VARCHAR(4) NOT NULL,

    quantity         NUMERIC(18,4) NOT NULL,

    price            NUMERIC(18,4) NOT NULL,

    trade_date       DATE NOT NULL,

    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    deleted_at       TIMESTAMPTZ,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    modified_at      TIMESTAMPTZ,

    CONSTRAINT pk_trades
        PRIMARY KEY (id, trade_date),

    CONSTRAINT fk_trade_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(id),

    CONSTRAINT fk_trade_counterparty
        FOREIGN KEY (counterparty_id)
        REFERENCES counterparties(id)

)
PARTITION BY RANGE (trade_date);

-- ============================================================================
-- STEP 3 - Monthly partitions
-- ============================================================================

CREATE TABLE trades_y2026m04
PARTITION OF trades
FOR VALUES FROM ('2026-04-01')
TO ('2026-05-01');

CREATE TABLE trades_y2026m05
PARTITION OF trades
FOR VALUES FROM ('2026-05-01')
TO ('2026-06-01');

CREATE TABLE trades_y2026m06
PARTITION OF trades
FOR VALUES FROM ('2026-06-01')
TO ('2026-07-01');

CREATE TABLE trades_y2026m07
PARTITION OF trades
FOR VALUES FROM ('2026-07-01')
TO ('2026-08-01');

-- ============================================================================
-- STEP 4 - Default partition
-- ============================================================================

CREATE TABLE trades_default
PARTITION OF trades
DEFAULT;

-- ============================================================================
-- STEP 5 - Supporting indexes
-- ============================================================================

CREATE INDEX idx_trades_trade_date
ON trades (trade_date);

CREATE INDEX idx_trades_instrument
ON trades (instrument_id);

CREATE INDEX idx_trades_counterparty
ON trades (counterparty_id);

CREATE INDEX idx_trades_status
ON trades (status);

CREATE INDEX idx_trades_asset_class
ON trades (asset_class);

-- ============================================================================
-- STEP 6 - Copy existing data
-- ============================================================================

INSERT INTO trades
(
    id,
    trade_ref,
    instrument_id,
    counterparty_id,
    asset_class,
    side,
    quantity,
    price,
    trade_date,
    status,
    deleted_at,
    created_at,
    modified_at
)
SELECT
    id,
    trade_ref,
    instrument_id,
    counterparty_id,
    asset_class,
    side,
    quantity,
    price,
    trade_date,
    status,
    deleted_at,
    created_at,
    modified_at
FROM trades_legacy;

-- ============================================================================
-- STEP 7 - Verify row counts
-- ============================================================================

SELECT
    COUNT(*) AS legacy_row_count
FROM trades_legacy;

SELECT
    COUNT(*) AS partitioned_row_count
FROM trades;

-- ============================================================================
-- STEP 8 - Verify partition distribution
-- ============================================================================

SELECT
    tableoid::regclass AS partition_name,
    COUNT(*) AS total_rows
FROM trades
GROUP BY tableoid
ORDER BY partition_name;

-- ============================================================================
-- STEP 9 - Verify partition pruning
-- ============================================================================

EXPLAIN ANALYZE
SELECT *
FROM trades
WHERE trade_date = DATE '2026-06-15';

COMMIT;

